import { StyleSheet } from "react-native";
export const fonts = StyleSheet.create({
  pageHeading1: {
    fontFamily: "Rubik-Medium",
    fontStyle: "normal",
    fontWeight: "500",
    fontSize: 32,
    lineHeight: 38,
  },
  pageHeading2: {
    fontFamily: "Rubik-Medium",
    fontStyle: "normal",
    fontWeight: "500",
    fontSize: 22,
    lineHeight: 26,
  },
  pageHeading3: {
    fontFamily: "Rubik-Medium",
    fontStyle: "normal",
    fontWeight: "500",
    fontSize: 20,
    lineHeight: 24,
  },
  body1: {
    fontFamily: "Rubik-Regular",
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: 18,
    lineHeight: 21,
  },
  body2: {
    fontFamily: "Rubik-Regular",
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: 16,
    lineHeight: 19,
  },
  Title1: {
    fontFamily: "Rubik-Medium",
    fontStyle: "normal",
    fontWeight: "500",
    fontSize: 18,
    lineHeight: 21,
  },
  Title2: {
    fontFamily: "Rubik-Medium",
    fontStyle: "normal",
    fontWeight: "500",
    fontSize: 16,
    lineHeight: 19,
  },
  Title3: {
    fontFamily: "Rubik-Medium",
    fontStyle: "normal",
    fontWeight: "500",
    fontSize: 14,
    lineHeight: 17,
  },
  Title4: {
    fontFamily: "Rubik-Regular",
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: 14,
    lineHeight: 17,
  },
  subtitle: {
    fontFamily: "Rubik-Regular",
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: 12,
    lineHeight: 14,
  },
});
